#!/usr/bin/env zsh
export DOTFILES=$HOME/dotfiles
export STOW_FOLDERS="nvim,zsh,powerlevel10k"

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    echo "Installing $folder"
    stow -R $folder
done
popd
